version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: Todo-Application
    environment:
      POSTGRES_DB: Todos
      POSTGRES_USERNAME: krishna
      POSTGRES_PASSWORD: 458336
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    restart: always

volumes:
  postgres-data:



